apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: vllm-model
spec:
  predictor:
    model:
      modelFormat:
        name: pytorch
      runtime: vllm
      storage:
        key: localModel
